### ISSUE TITLE
make package dependencies more declarative/obvious?

### ISSUE THREAD

**Issue by diablodale** [diablodale/gnucash-dev-docker#4]
Rather than use externals info like `apt-get build-dep -qq gnucash` should these build containers explicitly list the packages needed?

For example, `libofx-dev` is needed on debian/ubuntu and is being silently installed as part of some other packages dependencies. https://wiki.gnucash.org/wiki/BuildUbuntu16.04

**Comment by bhardwajs** [comment]
I am in favor of making dependencies explicit.

**Comment by diablodale** [comment]
Agreed. The recent additions for CentOS and openSUSE have more detailed and categorized dependencies. I'll update the others in a similar way.

I might also link disabled/enabled features (e.g. online banking, python bindings, etc.) to the categorized dependencies. I want to be sure the configuration usage is consistent with gnucash build scripts, easy to configure, and correctly re-builds the image if a feature state is changed.

**Comment by diablodale** [comment]
fixed with the last commit being https://github.com/diablodale/gnucash-dev-docker/commit/6300244c8132c641df7719b6d8ad34e9bb16ac66
