### ISSUE TITLE
docker help

### ISSUE THREAD

**Issue by christopherlam** [diablodale/gnucash-dev-docker#8]
Hi, sorry to annoy you on this; you've got some good docker skills. I'm trying to improve my dev environment to use docker better, so that I can hack on Gnucash better :)

Here's my current Dockerfile attempt. Basically I want to cache the build artefacts, so that hacking->make doesn't require compiling all files. Is this feasible within Docker?

```dockerfile
# Stage 1: Build GnuCash and cache build artifacts
FROM ubuntu
WORKDIR /app
# Update the package lists and install build dependencies
RUN apt-get update && \
    apt-get install -y build-essential \
                       cmake \
                       libgtk2.0-dev \
                       libxml2-dev \
                       libxslt-dev \
                       guile-2.2-dev
RUN apt-get install -y libboost-all-dev \
                       libdbi-dev \
                       libdbd-sqlite3 \
                       libdbd-pgsql \
                       libaqbanking-dev \
                       gwenhywfar-tools \
                       libgoffice-0.10-dev \
                       libboost-dev
RUN apt-get install -y libboost-all-dev \
                       python3-dev \
                       libgnomecanvas2-dev \
                       guile-2.2-dev \
                       libgirepository1.0-dev \
                       libwebkit2gtk-4.0-dev \
                       libosp-dev
RUN apt-get install -y libboost-all-dev \
                       swig \
                       gtk-doc-tools \
                       docbook-xsl \
                       docbook-xml \
                       libsoup2.4-dev
RUN apt-get install -y libboost-all-dev \
                       libwebkit2gtk-4.0-dev \
                       libsecret-1-dev \
                       itstool \
                       gettext \
                       libwebkit2gtk-4.0-dev \
                       git \
                       zip
RUN apt-get install -y libofx-dev googletest

COPY . /app
RUN cd /app
RUN mkdir -p build && cd build && cmake -DWITH_AQBANKING=OFF .. && make -j4 && make install
# --mount=type=cache,target=./build,sharing=locked \

CMD ["/app/build/bin/gnucash"]

ENTRYPOINT ["/app/build/bin/gnucash"]
```

Wish to design the following: (In pseudo code)

"rebuild" stage
- load dependencies
- copy . /app (i.e. load repo)
- cmake (i.e. create build dir - must be persistent)
- make (compile build into executables - must be persistent)

"hacking" stage
- copy build, executables from above
- copy . /app (i.e. refresh repo)
- make (efficient recompilation of changed source code only)
- make install
- copy installation files into folder outside container.

Thus I'd want to run "rebuild" once, then "hacking" during heavy development. Many thanks for considering!

**Comment by diablodale** [comment]
Hi. We privately emailed each other in December 2020. I recommend you read our last email...for context.

I do not contribute any significant think or code time to GnuCash. The GnuCash team must first resolve topics important to me, like https://bugs.gnucash.org/show_bug.cgi?id=798994.

**Comment by christopherlam** [comment]
In my last email I found no mutual animosity at all. Still the same. This bug 798994 I have no idea - Perl isn't my field. No offence taken if there's little CPU time anymore.

**Comment by diablodale** [comment]
Agreed, I have no animosity directed to you specifically. I hope you enjoy your growth in developing open-source software.

Instead, to quote myself from our email, "...some core team members is unproductive -- wasting my time". And therefore, I protect myself from such waste. I've seen these team members continue their unproductive and abusive behavior also toward other people -- quite publically. I caution everyone regarding that core team.
